### ISSUE TITLE
Considering using resvg-js instead of node-canvas?

### ISSUE THREAD

**Issue by yisibl** [catdad-experiments/svg-render#8]
Hi

Have you considered using [resvg-js](https://github.com/yisibl/resvg-js) instead of node-canvas? resvg is almost the fastest and most compatible SVG library.

node-canvas relies on node-gyp and postinstall, and has to be recompiled every time you install it if the version of gcc on your machine is too low. This makes for a very bad user experience.

In some scenarios,`resvg-js` is even faster than sharp.

## Benchmark

```shell
Running "resize width" suite...
  resvg-js(Rust):
    12 ops/s, ±22.66%   | fastest 🚀

  sharp:
    9 ops/s, ±64.52%    | 25% slower

  skr-canvas(Rust):
    7 ops/s, ±3.72%    | 41.67% slower

  svg2img(canvg and node-canvas):
    6 ops/s, ±16.94%    | slowest, 50% slower
```

**Comment by catdad** [comment]
Please do not promote your own library in my issue tracker. This has nothing to do with my library.
